### ISSUE TITLE
Image upload fails

### ISSUE THREAD

**Issue by poVoq** [QuantumObject/docker-ushahidi-platform#10]
Can't post images to a survey, the survey gets posted fine, but no image is attached using Firefox and a Chromium based Android browser. Might be related to the CORS header issue.

**Comment by angelrr7702** [comment]
yes, it appear that some location for some folder  where suppose to be before  change and my build process try the old location and fail ... 

[91mcp: cannot stat 'platform/application/config/init.php': No such file or directory
sed: can't read platform/application/config/environments/development/init.php: No such file or directory
sed: can't read platform/application/bootstrap.php: No such file or directory
[0m
[91mchown: cannot access 'platform/application/logs': No such file or directory
chown: cannot access 'platform/application/cache': No such file or directory
chown: cannot access 'platform/application/media/uploads': No such file or directory
chmod: cannot access 'platform/application/logs': No such file or directory
chmod: cannot access 'platform/application/cache': No such file or directory
chmod: cannot access 'platform/application/media/uploads': No such file or directory

**Comment by poVoq** [comment]
Oh, yes that part seems to have changed complete with the new lumen framework :(

**Comment by angelrr7702** [comment]
appear working with some problem for https continue at https://github.com/QuantumObject/docker-ushahidi-platform/issues/15
