### ISSUE TITLE
bash command error on Dockerfile

### ISSUE THREAD

**Issue by lupa18** [QuantumObject/docker-ushahidi-platform#2]
Hello ! 
I downloaded dockerfile and make some changes to apache port, then I used build command to make the image and got an error related with line 60 of Dockerfile: 
/bin/bash: /sbin/pre-conf: /bin/bash: bad interpreter: Text file busy

Then I removed -c flag from bash command and it seems to be working.

**Comment by angelrr7702** [comment]
I will try to rebuild the container again and check if fail ..

**Comment by angelrr7702** [comment]
This problem don't appear at build from docker trusted container .. It maybe relate to the version of docker  or Linux you are using for the build .. I will keep the way it is at the moment .
