### ISSUE TITLE
getting error source not found

### ISSUE THREAD

**Issue by lupa18** [QuantumObject/docker-ushahidi-platform#3]
I'm not sure if it's important, but when running the container I get this error: 
ushahidi-platform8082 | *** Running /etc/my_init.d/startup.sh...
ushahidi-platform8082 | already configured
ushahidi-platform8082 | *** Running /etc/rc.local...
ushahidi-platform8082 | *** Booting runit daemon...
ushahidi-platform8082 | *** Runit started as PID 7
ushahidi-platform8082 | trap: SIGKILL: bad trap
ushahidi-platform8082 | ./run: 9: ./run: source: not found

**Comment by angelrr7702** [comment]
I will check, did the container fail .. ? remember you need to deploy the client too ..

**Comment by lupa18** [comment]
No. It works. I got some errors but seems to be ushahidi problems and I reported as issues in their repo.

**Comment by angelrr7702** [comment]
Thanks, in this week I will rebuild/update container .. to make sure it have the last source from ushahidi

**Comment by angelrr7702** [comment]
done , update and working
