### ISSUE TITLE
Problem with fresh deployment, no admin/admin or user signup possible

### ISSUE THREAD

**Issue by poVoq** [QuantumObject/docker-ushahidi-platform#7]
First I updated my previous docker image and while I lost all user account data (was only a test install), it seem to have worked. But maybe it would be good to add the /var/lib/mysql volume for data persistence?

But the real issue is that I decided to completely recreate both the client and api container from scratch as a clean start, and while this seems to have worked fine at first glance, it is not possible to log in with admin/admin as before. It always says: "Login failed, check your email and password."

I also tried to create a new user, and that seems to work fine, but also the new user can't log in. However the user gets created, as I can't register the same user-email again.

I guess something is still wrong with the mcrypt lib for password hashing? I used the container from 2 days ago with the :latest tag.

**Comment by poVoq** [comment]
Thanks for adding the database volume.
I still can't log in with admin/admin though.
Might we an issue with Ushahidi though as in their gitter chat another person showed up with the exact same issue that doesn't use these docker images at all.

**Comment by angelrr7702** [comment]
Yes , I have been checking issue from ushahidi platform and still no find the real reason that login fail ...any clue you can find maybe help me to fix this container ..

I was able to update all my container in the last few two week , this the only one that still complete fail .

**Comment by poVoq** [comment]
I guess it might be related to using the "develop" branch for the platform-client together with the pre-release v3.12.3 version of the platform-api that is still based on the much older "production" branch?
Did you try using the platform-api "develop" branch as well?

**Comment by angelrr7702** [comment]
That is what I have before ... but that fail to work , maybe I try again ...

**Comment by angelrr7702** [comment]
"develop" branch for some reason fail to get the 
 
echo "
DB_HOST=localhost
DB_NAME=ushahidi
DB_USER=ushahidiuser
DB_PASS=ushahidipasswd
DB_TYPE=MySQLi
 " > /var/www/platform/.env

to the composer when used don't pass the database  configuration to it for some reason ...

**Comment by poVoq** [comment]
Yes strange. It seems to be able to read the database when there is old data in the volume, but if you wipe that data than it fails completely. I also tried passing the ENV parameters dynamically at container runtime, but same issue.

**Comment by poVoq** [comment]
The Ushahidi support pointed me to this new ENV parameters:
https://github.com/ushahidi/platform/blob/develop/.env.example

**Comment by angelrr7702** [comment]
thanks

**Comment by poVoq** [comment]
Just tried the new image. That makes it load again, but login and signup is still broken here.
But this is good progress, thanks a lot!

**Comment by angelrr7702** [comment]
I still missing this part : 
you will need to add the following lines to /etc/hosts:
127.0.0.1    localhost  platform-api    api.ushahidi.test

that is not possible inside of the docker container .,   /etc/hosts will be generate automatic by docker and any change will be loose .  need to find a way around it . 

the other difference is that I using Ubuntu 18.04 in the client .  when platform is 16.04   (platform can't be  18.04 because php-encrypt is missing ..)

**Comment by angelrr7702** [comment]
I was able to tested this morning and working ,,,, admin admin still initial login , them ask to add email for admin .... I was able to replace password for admin and to add a new user.

remember client take some time before it is running ..to work .

**Comment by poVoq** [comment]
From Ushahidi support:
> for those in Ubuntu 18.04 , Sury’s PPA is probably the best solution: https://launchpad.net/~ondrej/+archive/ubuntu/php . That way it’s possible to install php 7.0 or 7.1

**Comment by poVoq** [comment]
Hmm, odd. On a fresh install? Let me try to redo it, because for me it is still failing so far...
